"""add brand table and update user table

Revision ID: 9b3fd0b615b3
Revises: 33c1f6d74b81
Create Date: 2026-04-20 11:56:36.840908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b3fd0b615b3'
down_revision: Union[str, Sequence[str], None] = '33c1f6d74b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'basic', 'pro', name='brandplan'), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_brand_code'), 'brand', ['brand_code'], unique=True)
    op.add_column('user', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('is_developer', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.execute("CREATE TYPE userrole AS ENUM ('super_admin', 'admin', 'staff')")
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('super_admin', 'admin', 'staff', name='userrole'),
               existing_nullable=False,
               postgresql_using="role::userrole")
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_foreign_key(None, 'user', 'brand', ['brand_id'], ['id'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'staff', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.execute("DROP TYPE userrole")
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_developer')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'username')
    op.drop_column('user', 'brand_id')
    op.drop_index(op.f('ix_brand_brand_code'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
